exclude: [Gemfile, Gemfile.lock, Readme.md]
force_polling: true
host: 0.0.0.0
collections:
  books:
    output: true
defaults:
  -
    scope:
      path: ''
      type: books
    values:
      layout: page
      permalink: /title/:path/
